// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpp0zcCSMRZwqTjUDRImPgAFz8YsEPLM',
    appId: '1:256416420291:web:52ab8f3cf8976087436d76',
    messagingSenderId: '256416420291',
    projectId: 'propay-47fa1',
    authDomain: 'propay-47fa1.firebaseapp.com',
    storageBucket: 'propay-47fa1.firebasestorage.app',
    measurementId: 'G-0NYVBG27GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4TYi81HUf7QEnaQmJQiKGEnfWJZfUbCY',
    appId: '1:256416420291:android:7cc0cd40fd096d9a436d76',
    messagingSenderId: '256416420291',
    projectId: 'propay-47fa1',
    storageBucket: 'propay-47fa1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp4azyc2EWytnrHAYP-VPeV7OTDxVgwmE',
    appId: '1:256416420291:ios:c9af2e3ade5c1a3d436d76',
    messagingSenderId: '256416420291',
    projectId: 'propay-47fa1',
    storageBucket: 'propay-47fa1.firebasestorage.app',
    iosBundleId: 'com.example.propay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp4azyc2EWytnrHAYP-VPeV7OTDxVgwmE',
    appId: '1:256416420291:ios:c9af2e3ade5c1a3d436d76',
    messagingSenderId: '256416420291',
    projectId: 'propay-47fa1',
    storageBucket: 'propay-47fa1.firebasestorage.app',
    iosBundleId: 'com.example.propay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpp0zcCSMRZwqTjUDRImPgAFz8YsEPLM',
    appId: '1:256416420291:web:64948b36659cadc3436d76',
    messagingSenderId: '256416420291',
    projectId: 'propay-47fa1',
    authDomain: 'propay-47fa1.firebaseapp.com',
    storageBucket: 'propay-47fa1.firebasestorage.app',
    measurementId: 'G-SXPV6F3YDC',
  );
}
